version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: onja
      POSTGRES_DB: mlr1
    ports:
      - 5432:5432

  backend:
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: onja
      DB_DATABASE: mlr1

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
